---
title: "SPSS Attitudes Measure Validation"
author: "Carmen Dang"
date: "13/07/2020"
output: html_document
        md_keep = TRUE
---

```{r Loading Packages, echo = FALSE}
library(readr)
library(haven)
library(tidyverse)
library(lavaan)
library(psych)
library(mirt)
library(rsample)
```

```{r Uploading data and cleaning}
# Uploading raw data
full.data <- readxl::read_xlsx("spssdata.xlsx", col_names = TRUE)
# Remove empty rows
full.data <- full.data[1:181, ]

# Selecting only SPSS-related columns
  # Do not select StudentIDE col bc it'd be included with EFA/CFA
  # Num of rows corresponds to StudentIDE
spss.data <- full.data %>% 
             select(SPSS1E,
                    SPSS2E,
                    SPSS3E,
                    SPSS4E,
                    SPSS5E,
                    SPSS6E,
                    SPSS7E,
                    SPSS8E,
                    SPSS9E,
                    SPSS10E)

# Reverse code SPSS items 2, 3, 10
spss.data$SPSS2E <- car::recode(spss.data$SPSS2E, "1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1")
spss.data$SPSS3E <- car::recode(spss.data$SPSS3E, "1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1")
spss.data$SPSS10E <- car::recode(spss.data$SPSS10E, "1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1")
```

```{r Descriptive Stats}
describe(spss.data)

# Contingency table of the counts
table(spss.data$SPSS1E)
table(spss.data$SPSS2E)
table(spss.data$SPSS3E)
table(spss.data$SPSS4E)
table(spss.data$SPSS5E)
table(spss.data$SPSS6E)
table(spss.data$SPSS7E)
table(spss.data$SPSS8E)
table(spss.data$SPSS9E)
table(spss.data$SPSS10E)

## Missing Data Calculations ##
table(is.na(spss.data))

# FALSE  TRUE 
#  1988     3

# 3 / (3 + 1988) = 0.001506781
# 0.001506781 * 100 = 0.1506781

## Less than 1% missing data, proceeding with complete case analyses
```

```{r Splitting into EFA/CFA Sets}
# Default split is 75%/25%
# Default is no appropriate with our n = 181
# Zach suggests: EFA n = 81 and CFA n = 100
EFA_CFA_spss_split <- initial_split(spss.data, prop = .552)

EFA.spss <- testing(EFA_CFA_spss_split)
CFA.spss <- training(EFA_CFA_spss_split)
```

# Pearson Correlations

```{r MAP/Parallel}
VSS(EFA.spss, plot = F)
# 
# Very Simple Structure
# Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
#     n.obs = n.obs, plot = plot, title = title, use = use, cor = cor)
# VSS complexity 1 achieves a maximimum of 0.89  with  2  factors
# VSS complexity 2 achieves a maximimum of 0.95  with  5  factors
# 
# The Velicer MAP achieves a minimum of 0.05  with  2  factors 
# BIC achieves a minimum of  NA  with  2  factors
# Sample Size adjusted BIC achieves a minimum of  NA  with  4  factors


fa.parallel(EFA.spss, fm="ml", fa='both', n.iter=100)
# Statistics by number of factors 
# Parallel analysis suggests that the number of factors =  2  and the number of components =  2 
# If num. of components = NA bc fa = 'fa' produces factors, fa = 'pc' produces components, fa = 'both'
```

```{r EFAs}
# Zach prefers promax rotation. Promax is most common, but does not achieve a simple structure as well as other oblique rotations
  # Alyssa prefers oblimin
# fm. minres/ULS (default) does not assume multivariate normality, ML does.
  # Let's do ULS for now until assumptions are checked
```

```{r 1f uls oblimin}
fa(EFA.spss, nfactors = 1, fm = "uls", rotate = "oblimin")
# Factor Analysis using method =  uls
# Call: fa(r = EFA.spss, nfactors = 1, rotate = "oblimin", fm = "uls")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                ULS1
# SS loadings    4.38
# Proportion Var 0.44
# 
# Mean item complexity =  1
# Test of the hypothesis that 1 factor is sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 35  and the objective function was  1.45 
# 
# The root mean square of the residuals (RMSR) is  0.14 
# The df corrected root mean square of the residuals is  0.16 
# 
# The harmonic number of observations is  81 with the empirical chi square  146.13  with prob <  1.6e-15 
# The total number of observations was  81  with Likelihood Chi Square =  109.1  with prob <  1.5e-09 
# 
# Tucker Lewis Index of factoring reliability =  0.772
# RMSEA index =  0.161  and the 90 % confidence intervals are  0.129 0.198
# BIC =  -44.7
# Fit based upon off diagonal values = 0.9
# Measures of factor score adequacy             
#                                                   ULS1
# Correlation of (regression) scores with factors   0.97
# Multiple R square of scores with factors          0.94
# Minimum correlation of possible factor scores     0.88
#
#         ULS1      h2        u2      com
# SPSS1E	0.86	0.74552130	0.2544787	1     
# SPSS2E	0.09	0.00858251	0.9914175	1     ULS1 + h2 <.4 | ULS1 < .29
# SPSS3E	0.32	0.10491166	0.8950883	1     ULS1 + h2 <.4
# SPSS4E	0.91	0.81917893	0.1808211	1
# SPSS5E	0.71	0.50122542	0.4987746	1
# SPSS6E	0.65	0.42209038	0.5779096	1
# SPSS7E	0.56	0.31257203	0.6874280	1     h2 <.4
# SPSS8E	0.84	0.71224267	0.2877573	1
# SPSS9E	0.87	0.75122549	0.2487745	1
# SPSS10E	0.06	0.00359231	0.9964077	1     ULS1 + h2 <.4 | ULS1 < .29

##########
## 1F model looks terrible. RMSR should be <.08
## Explains 44% of data
## Several factor loadings <.40 (Zach drops these items and re-runs EFA)
## Several communalities <.40 (variance of measure explained by common factors)
## 1F so no point in rotating
##########
```
```{r 2f uls oblimin}
fa(EFA.spss, nfactors = 2, fm = "uls", rotate = "oblimin")

# Factor Analysis using method =  uls
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "oblimin", fm = "uls")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                       ULS1 ULS2
# SS loadings           4.33 1.65
# Proportion Var        0.43 0.17
# Cumulative Var        0.43 0.60
# Proportion Explained  0.72 0.28
# Cumulative Proportion 0.72 1.00
# 
#  With factor correlations of 
#      ULS1 ULS2
# ULS1 1.00 0.18
# ULS2 0.18 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 26  and the objective function was  0.5 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.05 
# 
# The harmonic number of observations is  81 with the empirical chi square  12.48  with prob <  0.99 
# The total number of observations was  81  with Likelihood Chi Square =  37.48  with prob <  0.068 
# 
# Tucker Lewis Index of factoring reliability =  0.952
# RMSEA index =  0.073  and the 90 % confidence intervals are  0 0.124
# BIC =  -76.77
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                   ULS1 ULS2
# Correlation of (regression) scores with factors   0.97 0.91
# Multiple R square of scores with factors          0.94 0.82
# Minimum correlation of possible factor scores     0.88 0.64

#         ULS1  ULS2    h2        u2      com
# SPSS1E	0.83	0.11	0.7396673	0.2603327	1.034476
# SPSS2E	-0.06	0.62	0.3751281	0.6248719	1.021075     h2 <.4
# SPSS3E	0.16	0.81	0.7225141	0.2774859	1.074621
# SPSS4E	0.91	0.00	0.8236385	0.1763615	1.000032
# SPSS5E	0.71	0.01	0.5005313	0.4994687	1.000326
# SPSS6E	0.67	-0.05	0.4338667	0.5661333	1.013136
# SPSS7E	0.57	-0.04	0.3201593	0.6798407	1.011762     h2 <.4
# SPSS8E	0.82	0.10	0.7071139	0.2928861	1.029822
# SPSS9E	0.91	-0.11	0.8003972	0.1996028	1.031578
# SPSS10E	-0.13	0.76	0.5547013	0.4452987	1.061648

##########
# RMSR = .04 is good
# 2F explains 60% var, that is a 16% increase
# All factor loadings are >.4
# Some w. low communality
# Let's check out other rotations to change the loadings
##########
```
```{r 2f uls promax}
fa(EFA.spss, nfactors = 2, fm = "uls", rotate = "promax")

# Factor Analysis using method =  uls
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "promax", fm = "uls")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                       ULS1 ULS2
# SS loadings           4.34 1.64
# Proportion Var        0.43 0.16
# Cumulative Var        0.43 0.60
# Proportion Explained  0.73 0.27
# Cumulative Proportion 0.73 1.00
# 
#  With factor correlations of 
#      ULS1 ULS2
# ULS1 1.00 0.14
# ULS2 0.14 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 26  and the objective function was  0.5 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.05 
# 
# The harmonic number of observations is  81 with the empirical chi square  12.48  with prob <  0.99 
# The total number of observations was  81  with Likelihood Chi Square =  37.48  with prob <  0.068 
# 
# Tucker Lewis Index of factoring reliability =  0.952
# RMSEA index =  0.073  and the 90 % confidence intervals are  0 0.124
# BIC =  -76.77
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                   ULS1 ULS2
# Correlation of (regression) scores with factors   0.97 0.91
# Multiple R square of scores with factors          0.94 0.82
# Minimum correlation of possible factor scores     0.88 0.64

#         ULS1  ULS2      h2        u2      com
# SPSS1E	0.84	0.11	0.7396673	0.2603327	1.035452
# SPSS2E	-0.04	0.62	0.3751281	0.6248719	1.008733
# SPSS3E	0.19	0.80	0.7225141	0.2774859	1.106742
# SPSS4E	0.91	0.00	0.8236385	0.1763615	1.000001
# SPSS5E	0.71	0.01	0.5005313	0.4994687	1.000505
# SPSS6E	0.66	-0.05	0.4338667	0.5661333	1.012057
# SPSS7E	0.57	-0.04	0.3201593	0.6798407	1.010741
# SPSS8E	0.82	0.10	0.7071139	0.2928861	1.030797
# SPSS9E	0.90	-0.11	0.8003972	0.1996028	1.029939
# SPSS10E	-0.10	0.75	0.5547013	0.4452987	1.038919

##########
# Factor loadings did not change much
# Open to trying other rotations as well
##########
```
```{r Assumptions}
# NOTE: not very confident abt assumptions - need some guidance

# ML assumptions
  # "multicollinearity" - factors should be highly correlated, but not = 1
  # Aiming for a significant Bartlett's test
    # Not usually tested bc EFA requires large N which usually makes Bartlett's test sig.
correlations = cor(EFA.spss, use = "complete.obs")
cortest.bartlett(correlations, n = nrow(EFA.spss))
# linearity assumptions
  # TBD
# observed variables are multivariate normality
MVN::mvn(EFA.spss)
  # Output: multivariate tests + p vals, univariate normality, descriptive stats

# Other assumptions
  # Large enough sample size?
    # .9+ = yay, .8 = yayish, .7 = ok, .6 = meh, <.5 = bad
KMO(correlations)
  # Need at least 3-4 items per factor
```

# Let's try ml..

```{r}
fa(EFA.spss, nfactors = 1, fm = "ml", rotate = "oblimin")
# 
# Factor Analysis using method =  ml
# Call: fa(r = EFA.spss, nfactors = 1, rotate = "oblimin", fm = "ml")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                 ML1
# SS loadings    4.36
# Proportion Var 0.44
# 
# Mean item complexity =  1
# Test of the hypothesis that 1 factor is sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 35  and the objective function was  1.43 
# 
# The root mean square of the residuals (RMSR) is  0.14 
# The df corrected root mean square of the residuals is  0.16 
# 
# The harmonic number of observations is  81 with the empirical chi square  149.67  with prob <  3.9e-16 
# The total number of observations was  81  with Likelihood Chi Square =  107.39  with prob <  2.8e-09 
# 
# Tucker Lewis Index of factoring reliability =  0.777
# RMSEA index =  0.159  and the 90 % confidence intervals are  0.127 0.196
# BIC =  -46.41
# Fit based upon off diagonal values = 0.9
# Measures of factor score adequacy             
#                                                    ML1
# Correlation of (regression) scores with factors   0.97
# Multiple R square of scores with factors          0.94
# Minimum correlation of possible factor scores     0.89
# 

#         ML1       h2            u2  com
# SPSS1E	0.86	0.7435789512	0.2564210	1   
# SPSS2E	0.04	0.0012337124	0.9987663	1   ML1 <.4 | h2 <.4 | ML1 < .29
# SPSS3E	0.32	0.1000876158	0.8999124	1   ML1 <.4 | h2 <.4
# SPSS4E	0.92	0.8486042664	0.1513957	1
# SPSS5E	0.70	0.4906327942	0.5093672	1
# SPSS6E	0.66	0.4295388279	0.5704612	1
# SPSS7E	0.54	0.2965556374	0.7034444	1   h2 <.4
# SPSS8E	0.81	0.6632291405	0.3367709	1
# SPSS9E	0.89	0.7876013660	0.2123986	1
# SPSS10E	0.02	0.0005946782	0.9994053	1   ML1 <.4 | h2 <.4 | ML1 < .29

##########
# RMSR <.14
# explains 44% of var
# many factor loadings <.4, some <.29
# some communality <.4
##########
```
```{r}
fa(EFA.spss, nfactors = 2, fm = "ml", rotate = "oblimin")

# Factor Analysis using method =  ml
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "oblimin", fm = "ml")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        ML1  ML2
# SS loadings           4.31 1.65
# Proportion Var        0.43 0.16
# Cumulative Var        0.43 0.60
# Proportion Explained  0.72 0.28
# Cumulative Proportion 0.72 1.00
# 
#  With factor correlations of 
#      ML1  ML2
# ML1 1.00 0.16
# ML2 0.16 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 26  and the objective function was  0.48 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.06 
# 
# The harmonic number of observations is  81 with the empirical chi square  14.03  with prob <  0.97 
# The total number of observations was  81  with Likelihood Chi Square =  36.04  with prob <  0.091 
# 
# Tucker Lewis Index of factoring reliability =  0.958
# RMSEA index =  0.068  and the 90 % confidence intervals are  0 0.12
# BIC =  -78.21
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                    ML1  ML2
# Correlation of (regression) scores with factors   0.97 0.90
# Multiple R square of scores with factors          0.95 0.81
# Minimum correlation of possible factor scores     0.89 0.61
# 
#         ML1   ML2       h2        u2      com
# SPSS1E	0.84	0.11	0.7442887	0.2557113	1.032725
# SPSS2E	-0.08	0.64	0.3961480	0.6038520	1.033308    h2 < .4
# SPSS3E	0.19	0.77	0.6793245	0.3206755	1.117093
# SPSS4E	0.92	0.00	0.8502506	0.1497494	1.000012
# SPSS5E	0.70	0.00	0.4855031	0.5144969	1.000022
# SPSS6E	0.67	-0.06	0.4348229	0.5651771	1.016416
# SPSS7E	0.55	-0.05	0.2978138	0.7021862	1.018181    h2 < .4
# SPSS8E	0.79	0.11	0.6706395	0.3293605	1.037396
# SPSS9E	0.92	-0.11	0.8180204	0.1819796	1.028175
# SPSS10E	-0.12	0.78	0.5874262	0.4125738	1.047000

##########
# RMSR = .04
# Explains 60% of var, that's a 16% increase
##########

```
```{r}
fa(EFA.spss, nfactors = 2, fm = "ml", rotate = "promax")

# Factor Analysis using method =  ml
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "promax", fm = "ml")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        ML1  ML2
# SS loadings           4.32 1.65
# Proportion Var        0.43 0.16
# Cumulative Var        0.43 0.60
# Proportion Explained  0.72 0.28
# Cumulative Proportion 0.72 1.00
# 
#  With factor correlations of 
#      ML1  ML2
# ML1 1.00 0.13
# ML2 0.13 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  6.15 with Chi Square of  466.51
# The degrees of freedom for the model are 26  and the objective function was  0.48 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.06 
# 
# The harmonic number of observations is  81 with the empirical chi square  14.03  with prob <  0.97 
# The total number of observations was  81  with Likelihood Chi Square =  36.04  with prob <  0.091 
# 
# Tucker Lewis Index of factoring reliability =  0.958
# RMSEA index =  0.068  and the 90 % confidence intervals are  0 0.12
# BIC =  -78.21
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                    ML1  ML2
# Correlation of (regression) scores with factors   0.97 0.90
# Multiple R square of scores with factors          0.95 0.81
# Minimum correlation of possible factor scores     0.89 0.61
# 
#          ML1   ML2       h2        u2      com
# SPSS1E	0.84	0.11	0.7442887	0.2557113	1.034661
# SPSS2E	-0.07	0.63	0.3961480	0.6038520	1.021465
# SPSS3E	0.21	0.77	0.6793245	0.3206755	1.143743
# SPSS4E	0.92	0.00	0.8502506	0.1497494	1.000009
# SPSS5E	0.70	0.01	0.4855031	0.5144969	1.000123
# SPSS6E	0.66	-0.06	0.4348229	0.5651771	1.014772
# SPSS7E	0.55	-0.05	0.2978138	0.7021862	1.016451
# SPSS8E	0.80	0.11	0.6706395	0.3293605	1.039414
# SPSS9E	0.91	-0.10	0.8180204	0.1819796	1.026036
# SPSS10E	-0.10	0.77	0.5874262	0.4125738	1.032749

##########
# Loadings did not change much from oblimin
##########
```

# Possibly method effects?

```{r drop reverse worded items}
EFA.spss.2 <- EFA.spss %>% select(-SPSS2E, -SPSS3E, -SPSS10E)
```

```{r rerun VSS/PA}
VSS(EFA.spss.2, plot = F)

fa.parallel(EFA.spss.2, fm="ml", fa='both', n.iter=100)


# Very Simple Structure
# Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
#     n.obs = n.obs, plot = plot, title = title, use = use, cor = cor)
# VSS complexity 1 achieves a maximimum of 0.94  with  1  factors
# VSS complexity 2 achieves a maximimum of 0.95  with  2  factors
# 
# The Velicer MAP achieves a minimum of NA  with  1  factors 
# BIC achieves a minimum of  NA  with  1  factors
# Sample Size adjusted BIC achieves a minimum of  NA  with  3  factors
# 
# Statistics by number of factors 
# Parallel analysis suggests that the number of factors =  1  and the number of components =  1 
```

```{r rerun EFA}
fa(EFA.spss.2, nfactors = 1, fm = "uls", rotate = "oblimin")

# Factor Analysis using method =  uls
# Call: fa(r = EFA.spss.2, nfactors = 1, rotate = "oblimin", fm = "uls")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                ULS1
# SS loadings    4.28
# Proportion Var 0.61
# 
# Mean item complexity =  1
# Test of the hypothesis that 1 factor is sufficient.
# 
# The degrees of freedom for the null model are  21  and the objective function was  4.85 with Chi Square of  373
# The degrees of freedom for the model are 14  and the objective function was  0.24 
# 
# The root mean square of the residuals (RMSR) is  0.03 
# The df corrected root mean square of the residuals is  0.04 
# 
# The harmonic number of observations is  81 with the empirical chi square  3.94  with prob <  1 
# The total number of observations was  81  with Likelihood Chi Square =  18.58  with prob <  0.18 
# 
# Tucker Lewis Index of factoring reliability =  0.98
# RMSEA index =  0.062  and the 90 % confidence intervals are  0 0.134
# BIC =  -42.94
# Fit based upon off diagonal values = 1
# Measures of factor score adequacy             
#                                                   ULS1
# Correlation of (regression) scores with factors   0.97
# Multiple R square of scores with factors          0.94
# Minimum correlation of possible factor scores     0.87
# 
#         ULS1      h2        u2    com
# SPSS1E	0.86	0.7336326	0.2663674	1
# SPSS4E	0.91	0.8202064	0.1797936	1
# SPSS5E	0.71	0.5045856	0.4954144	1
# SPSS6E	0.66	0.4339379	0.5660621	1
# SPSS7E	0.56	0.3174674	0.6825326	1
# SPSS8E	0.83	0.6968142	0.3031858	1
# SPSS9E	0.88	0.7721449	0.2278551	1

##########
# RMSR = .03
# Prop var explained: 61%
# No loadings <.4
# Some communality <.4, but none <.2
##########
```

# Polychoric Correlations

```{r}
psych::polychoric(EFA.spss)

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Call: psych::polychoric(x = EFA.spss)
# Polychoric correlations 
#         SPSS1E SPSS2 SPSS3 SPSS4 SPSS5 SPSS6 SPSS7 SPSS8 SPSS9 SPSS10
# SPSS1E   1.00                                                        
# SPSS2E   0.43   1.00                                                 
# SPSS3E   0.36   0.67  1.00                                           
# SPSS4E   0.57   0.27  0.28  1.00                                     
# SPSS5E   0.49   0.28  0.30  0.45  1.00                               
# SPSS6E   0.36   0.15  0.20  0.41  0.40  1.00                         
# SPSS7E   0.43   0.19  0.10  0.40  0.48  0.31  1.00                   
# SPSS8E   0.56   0.28  0.28  0.51  0.49  0.41  0.48  1.00             
# SPSS9E   0.57   0.29  0.27  0.56  0.47  0.37  0.41  0.57  1.00       
# SPSS10E  0.35   0.40  0.32  0.30  0.13 -0.03  0.03  0.24  0.17  1.00 
# 
#  with tau of 
#            1     2      3    4
# SPSS1E  -1.8 -1.04 -0.126 1.04
# SPSS2E  -2.0 -0.90 -0.397 0.81
# SPSS3E  -1.5 -0.99 -0.234 0.90
# SPSS4E  -2.2 -0.94  0.109 1.16
# SPSS5E  -2.0 -1.45 -0.234 0.81
# SPSS6E  -1.4 -0.99  0.015 0.81
# SPSS7E  -1.4 -0.61  0.109 0.81
# SPSS8E  -2.0 -1.16 -0.140 1.04
# SPSS9E  -2.2 -0.99  0.015 0.94
# SPSS10E -1.7 -0.72  0.046 1.04
```

```{r MAP/Parallel}
VSS(EFA.spss, fm = 'minres', cor = 'poly', plot = F)

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.
# Very Simple Structure
# Call: vss(x = x, n = n, rotate = rotate, diagonal = diagonal, fm = fm, 
#     n.obs = n.obs, plot = plot, title = title, use = use, cor = cor)
# VSS complexity 1 achieves a maximimum of 0.78  with  1  factors
# VSS complexity 2 achieves a maximimum of 0.87  with  2  factors
# 
# The Velicer MAP achieves a minimum of 0.04  with  1  factors 
# BIC achieves a minimum of  NA  with  2  factors
# Sample Size adjusted BIC achieves a minimum of  NA  with  2  factors
# 
# Statistics by number of factors

fa.parallel(EFA.spss, fm = 'minres', cor = 'poly', fa ='both', n.iter=100)

# ...The estimated weights for the factor scores are probably incorrect.  Try a different factor score estimation method.An ultra-Heywood case was detected.  Examine the results carefully45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.
#
# Parallel analysis suggests that the number of factors =  2  and the number of components =  2 
```

```{r onef}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 1)

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Factor Analysis using method =  minres
# Call: fa(r = EFA.spss, nfactors = 1, fm = "minres", cor = "poly")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                 MR1
# SS loadings    3.76
# Proportion Var 0.38
# 
# Mean item complexity =  1
# Test of the hypothesis that 1 factor is sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  3.8 with Chi Square of  288.2
# The degrees of freedom for the model are 35  and the objective function was  0.85 
# 
# The root mean square of the residuals (RMSR) is  0.1 
# The df corrected root mean square of the residuals is  0.12 
# 
# The harmonic number of observations is  81 with the empirical chi square  76.48  with prob <  6.4e-05 
# The total number of observations was  81  with Likelihood Chi Square =  63.55  with prob <  0.0022 
# 
# Tucker Lewis Index of factoring reliability =  0.847
# RMSEA index =  0.1  and the 90 % confidence intervals are  0.06 0.14
# BIC =  -90.25
# Fit based upon off diagonal values = 0.93
# Measures of factor score adequacy             
#                                                    MR1
# Correlation of (regression) scores with factors   0.94
# Multiple R square of scores with factors          0.88
# Minimum correlation of possible factor scores     0.76

#         MR1       h2        u2    com
# SPSS1E	0.79	0.6172494	0.3827506	1
# SPSS2E	0.50	0.2527229	0.7472771	1
# SPSS3E	0.47	0.2246721	0.7753279	1
# SPSS4E	0.72	0.5129039	0.4870961	1
# SPSS5E	0.66	0.4402027	0.5597973	1
# SPSS6E	0.49	0.2445146	0.7554854	1
# SPSS7E	0.55	0.3005827	0.6994173	1
# SPSS8E	0.73	0.5383807	0.4616193	1
# SPSS9E	0.71	0.5112138	0.4887862	1
# SPSS10E	0.34	0.1128328	0.8871672	1

```

```{r twof}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 2)

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Factor Analysis using method =  minres
# Call: fa(r = EFA.spss, nfactors = 2, fm = "minres", cor = "poly")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        MR1  MR2
# SS loadings           3.29 1.60
# Proportion Var        0.33 0.16
# Cumulative Var        0.33 0.49
# Proportion Explained  0.67 0.33
# Cumulative Proportion 0.67 1.00
# 
#  With factor correlations of 
#      MR1  MR2
# MR1 1.00 0.46
# MR2 0.46 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  3.8 with Chi Square of  288.2
# The degrees of freedom for the model are 26  and the objective function was  0.24 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.05 
# 
# The harmonic number of observations is  81 with the empirical chi square  12.1  with prob <  0.99 
# The total number of observations was  81  with Likelihood Chi Square =  18.18  with prob <  0.87 
# 
# Tucker Lewis Index of factoring reliability =  1.057
# RMSEA index =  0  and the 90 % confidence intervals are  0 0.047
# BIC =  -96.07
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                    MR1  MR2
# Correlation of (regression) scores with factors   0.93 0.91
# Multiple R square of scores with factors          0.87 0.83
# Minimum correlation of possible factor scores     0.75 0.66
# 
#         MR1   MR2       h2      u2        com
# SPSS1E	0.65	0.21	0.5985569	0.4014431	1.213902
# SPSS2E	-0.01	0.86	0.7427032	0.2572968	1.000072
# SPSS3E	0.04	0.72	0.5469524	0.4530476	1.005051
# SPSS4E	0.69	0.05	0.5193531	0.4806469	1.012167
# SPSS5E	0.68	0.01	0.4619481	0.5380519	1.000333
# SPSS6E	0.58	-0.11	0.2948620	0.7051380	1.065314
# SPSS7E	0.68	-0.16	0.3886479	0.6113521	1.107156
# SPSS8E	0.75	0.01	0.5661628	0.4338372	1.000176
# SPSS9E	0.73	0.01	0.5344979	0.4655021	1.000481
# SPSS10E	0.03	0.47	0.2369709	0.7630291	1.010499
```
```{r threef}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 3)

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Factor Analysis using method =  minres
# Call: fa(r = EFA.spss, nfactors = 3, fm = "minres", cor = "poly")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        MR1  MR2  MR3
# SS loadings           3.33 1.44 0.93
# Proportion Var        0.33 0.14 0.09
# Cumulative Var        0.33 0.48 0.57
# Proportion Explained  0.58 0.25 0.16
# Cumulative Proportion 0.58 0.84 1.00
# 
#  With factor correlations of 
#      MR1  MR2  MR3
# MR1 1.00 0.38 0.27
# MR2 0.38 1.00 0.36
# MR3 0.27 0.36 1.00
# 
# Mean item complexity =  1.1
# Test of the hypothesis that 3 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  3.8 with Chi Square of  288.2
# The degrees of freedom for the model are 18  and the objective function was  0.11 
# 
# The root mean square of the residuals (RMSR) is  0.02 
# The df corrected root mean square of the residuals is  0.04 
# 
# The harmonic number of observations is  81 with the empirical chi square  3.95  with prob <  1 
# The total number of observations was  81  with Likelihood Chi Square =  8.31  with prob <  0.97 
# 
# Tucker Lewis Index of factoring reliability =  1.103
# RMSEA index =  0  and the 90 % confidence intervals are  0 0
# BIC =  -70.79
# Fit based upon off diagonal values = 1
# Measures of factor score adequacy             
#                                                    MR1 MR2  MR3
# Correlation of (regression) scores with factors   0.94   1 0.87
# Multiple R square of scores with factors          0.87   1 0.76
# Minimum correlation of possible factor scores     0.75   1 0.53
# 
#         MR1   MR2   MR3       h2        u2        com
# SPSS1E	0.68	0.06	0.19	0.6127656	0.387234409	1.175643
# SPSS2E	0.12	0.56	0.21	0.5188486	0.481151433	1.387924
# SPSS3E	-0.02	1.01	-0.03	0.9961837	0.003816273	1.001711
# SPSS4E	0.70	-0.03	0.13	0.5338773	0.466122674	1.075298
# SPSS5E	0.67	0.09	-0.11	0.4740481	0.525951851	1.085722
# SPSS6E	0.58	0.06	-0.22	0.3296342	0.670365783	1.302773
# SPSS7E	0.67	-0.08	-0.12	0.3961572	0.603842805	1.093895
# SPSS8E	0.74	-0.01	0.03	0.5624311	0.437568946	1.003968
# SPSS9E	0.73	0.00	0.01	0.5333148	0.466685156	1.000244
# SPSS10E	0.02	0.03	0.84	0.7380883	0.261911740	1.003885
```

## Rotate 2f models (default: oblimin)

```{r}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 2, rotate = 'geominQ')

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Factor Analysis using method =  minres
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "geominQ", fm = "minres", 
#     cor = "poly")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        MR1  MR2
# SS loadings           3.27 1.63
# Proportion Var        0.33 0.16
# Cumulative Var        0.33 0.49
# Proportion Explained  0.67 0.33
# Cumulative Proportion 0.67 1.00
# 
#  With factor correlations of 
#      MR1  MR2
# MR1 1.00 0.45
# MR2 0.45 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  3.8 with Chi Square of  288.2
# The degrees of freedom for the model are 26  and the objective function was  0.24 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.05 
# 
# The harmonic number of observations is  81 with the empirical chi square  12.1  with prob <  0.99 
# The total number of observations was  81  with Likelihood Chi Square =  18.18  with prob <  0.87 
# 
# Tucker Lewis Index of factoring reliability =  1.057
# RMSEA index =  0  and the 90 % confidence intervals are  0 0.047
# BIC =  -96.07
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                    MR1  MR2
# Correlation of (regression) scores with factors   0.93 0.91
# Multiple R square of scores with factors          0.87 0.83
# Minimum correlation of possible factor scores     0.74 0.66
# 
#         MR1   MR2       h2      u2        com
# SPSS1E	0.65	0.22	0.5985569	0.4014431	1.233084
# SPSS2E	-0.01	0.86	0.7427032	0.2572968	1.000110
# SPSS3E	0.04	0.72	0.5469524	0.4530476	1.004693
# SPSS4E	0.69	0.06	0.5193531	0.4806469	1.016583
# SPSS5E	0.67	0.02	0.4619481	0.5380519	1.001304
# SPSS6E	0.58	-0.10	0.2948620	0.7051380	1.057318
# SPSS7E	0.68	-0.15	0.3886479	0.6113521	1.097140
# SPSS8E	0.74	0.02	0.5661628	0.4338372	1.000968
# SPSS9E	0.72	0.02	0.5344979	0.4655021	1.001586
# SPSS10E	0.03	0.47	0.2369709	0.7630291	1.009932

```

```{r}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 2, rotate = 'biquartimin')

# Error in matrix(1, k, k) : non-numeric matrix extent
```

```{r}
fa(r = EFA.spss, fm = 'minres', cor = 'poly', nfactors = 2, rotate = 'Promax') # Zach's fav. Allows for correlations between factors

# 45 cells were adjusted for 0 values using the correction for continuity. Examine your data carefully.Factor Analysis using method =  minres
# Call: fa(r = EFA.spss, nfactors = 2, rotate = "Promax", fm = "minres", 
#     cor = "poly")
# Standardized loadings (pattern matrix) based upon correlation matrix
# 
#                        MR1  MR2
# SS loadings           3.30 1.59
# Proportion Var        0.33 0.16
# Cumulative Var        0.33 0.49
# Proportion Explained  0.67 0.33
# Cumulative Proportion 0.67 1.00
# 
#  With factor correlations of 
#      MR1  MR2
# MR1 1.00 0.44
# MR2 0.44 1.00
# 
# Mean item complexity =  1
# Test of the hypothesis that 2 factors are sufficient.
# 
# The degrees of freedom for the null model are  45  and the objective function was  3.8 with Chi Square of  288.2
# The degrees of freedom for the model are 26  and the objective function was  0.24 
# 
# The root mean square of the residuals (RMSR) is  0.04 
# The df corrected root mean square of the residuals is  0.05 
# 
# The harmonic number of observations is  81 with the empirical chi square  12.1  with prob <  0.99 
# The total number of observations was  81  with Likelihood Chi Square =  18.18  with prob <  0.87 
# 
# Tucker Lewis Index of factoring reliability =  1.057
# RMSEA index =  0  and the 90 % confidence intervals are  0 0.047
# BIC =  -96.07
# Fit based upon off diagonal values = 0.99
# Measures of factor score adequacy             
#                                                    MR1  MR2
# Correlation of (regression) scores with factors   0.93 0.91
# Multiple R square of scores with factors          0.87 0.82
# Minimum correlation of possible factor scores     0.74 0.65
# 
#          MR1   MR2       h2      u2        com
# SPSS1E	0.66	0.21	0.5985569	0.4014431	1.210772
# SPSS2E	0.01	0.86	0.7427032	0.2572968	1.000498
# SPSS3E	0.05	0.72	0.5469524	0.4530476	1.010511
# SPSS4E	0.69	0.06	0.5193531	0.4806469	1.012752
# SPSS5E	0.68	0.01	0.4619481	0.5380519	1.000476
# SPSS6E	0.58	-0.10	0.2948620	0.7051380	1.062817
# SPSS7E	0.68	-0.15	0.3886479	0.6113521	1.103980
# SPSS8E	0.75	0.01	0.5661628	0.4338372	1.000286
# SPSS9E	0.73	0.01	0.5344979	0.4655021	1.000650
# SPSS10E	0.04	0.47	0.2369709	0.7630291	1.018004
```

